---
- name: Installer Nginx ou le mettre à jour
  hosts: localhost
  become: yes
  tasks:
    - name: Installer ou mettre à jour Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Vérifier si Nginx est en cours d'exécution
      systemd:
        name: nginx
        state: started
        enabled: yes
      register: nginx_status

    - name: Afficher le statut de Nginx
      debug:
        var: nginx_status
